FROM bitwalker/alpine-elixir-phoenix:1.6.5

LABEL maintainer="bonjour@civilcode.io"

# update package manager
RUN apk update \
    apk upgrade --no-cache

# install watchman
RUN apk add autoconf automake libtool python-dev linux-headers
RUN git clone https://github.com/facebook/watchman.git && \
   cd watchman && \
   git checkout v4.9.0 && \
  ./autogen.sh && \
  ./configure && \
  make && \
  make install

ENTRYPOINT ["sleep", "infinity"]
