FROM bitwalker/alpine-elixir-phoenix:1.7.3

LABEL maintainer="bonjour@civilcode.io"

# install watchman
RUN apk update && \
    apk upgrade --no-cache && \
    apk add autoconf automake libtool python-dev linux-headers

RUN git clone https://github.com/facebook/watchman.git && \
   cd watchman && \
   git checkout v4.9.0 && \
  ./autogen.sh && \
  ./configure && \
  make && \
  make install

RUN echo "cd /app && watchman -j < .watchman/format.json" >> ~/.bashrc

RUN mix do local.hex --force, local.rebar --force

CMD ["/bin/bash"]
